package com.hms.pharmacy.entity;


public enum MedicineCategory {
    // REGULATORY & LEGAL STATUS
    PRESCRIPTION_ONLY_MEDICINE,
    OVER_THE_COUNTER,
    CONTROLLED_SUBSTANCE,
    PHARMACY_ONLY,
    RESTRICTED_MEDICINE,

    // CLINICAL & THERAPEUTIC CLASSES
    ANTIBIOTICS,
    ANTIVIRALS,
    ANTIFUNGALS,
    ANALGESICS,
    ANTIPYRETICS,
    ANTISEPTICS,
    ANTIDEPRESSANTS,
    ANTI_HYPERTENSIVES,
    ANTI_DIABETICS,
    ANTIHISTAMINES,
    ANTI_INFLAMMATORIES,
    ANTICOAGULANTS,
    ANTICONVULSANTS,
    ANTINEOPLASTICS,

    // ADMINISTRATION ROUTES
    ORAL_MEDICINE,
    INJECTABLE,
    TOPICAL,
    INHALANTS,
    OPHTHALMIC,
    OTIC,
    NASAL,
    SUPPOSITORY,

    // SPECIAL CARE & BIOLOGICS
    DIETARY_SUPPLEMENTS,
    VACCINES,
    INTRAVENOUS_FLUIDS,
    ANESTHETICS,
    HORMONE_REPLACEMENT_THERAPY,
    HERBAL_MEDICINE,

    // SUPPLIES & CONSUMABLES
    MEDICAL_CONSUMABLES,
    DIAGNOSTIC_TOOLS,
    PERSONAL_CARE,
    SURGICAL_SUPPLIES,
    WOUND_CARE,

    // MISCELLANEOUS
    OTHERS
}
