server.port=9000
spring.application.name=GatewayMS

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin RETAIN_UNIQUE
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# Routes
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[0].filters[0]=TokenFilter

spring.cloud.gateway.routes[1].id=user-service-alias
spring.cloud.gateway.routes[1].uri=http://localhost:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[1].filters[0]=TokenFilter
spring.cloud.gateway.routes[1].filters[1]=RewritePath=/user/(?<segment>.*), /users/${segment}

# JWT (must match UserMS)
jwt.secret=eAl4qXamyfxUGhDDZUo3yh6yxqgGQOu9fFGHXeinTbldUL6rqF40VM1RjPl2Mh5xgZEIC0e21JZ5xwU4V3PX1N
