server.port=8080
spring.application.name=UserMS

# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/userdb
spring.datasource.username=root
spring.datasource.password=Lynxvi123.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret=eAl4qXamyfxUGhDDZUo3yh6yxqgGQOu9fFGHXeinTbldUL6rqF40VM1RjPl2Mh5xgZEIC0e21JZ5xwU4V3PX1N

# Error messages
USER_ALREADY_EXISTS=User with given email already exists
USER_NOT_FOUND=User not found
INVALID_CREDENTIALS=Invalid email or password
