spring.application.name=PharmacyMS
server.port=9300
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacydb
spring.datasource.username=root
spring.datasource.password=Lynxvi123.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA / Hibernate - schema managed manually (no Flyway)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
# Register with local Eureka Server
# (Needs Eureka-Server running on http://localhost:8761)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Explicit persistence/JPA settings to help Hibernate determine the dialect at bootstrap
jakarta.persistence.jdbc.url=jdbc:mysql://localhost:3306/pharmacydb
jakarta.persistence.jdbc.user=root
jakarta.persistence.jdbc.password=Lynxvi123.
# Use MySQL dialect (ensure compatibility with Hibernate distribution)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Kafka bootstrap servers (can be overridden with env KAFKA_BOOTSTRAP_SERVERS)
spring.kafka.bootstrap-servers=localhost:9093
kafka.bootstrap-servers=localhost:9093


eureka.instance.instance-id=${spring.application.name}:${server.port}

PHARMACY_NOT_FOUND=Pharmacy not found
MEDICINE_NOT_FOUND=Medicine not found
MEDICINE_ALREADY_EXISTS=Medicine already exists

# Swagger
springdoc.api-docs.path=/pharmacy/v3/api-docs